version: '3'

services:
  web:
    container_name: cybosium_web
    restart: always
    build:
      context: .
    volumes:
      - "./:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - "8000:8000"
    links:
      - mongo

  mongo:
    container_name: cybosium_mongo
    image: mongo
    ports:
      - "27017:27017"
