version: '3'

services:
  web:
    container_name: cybosium_web
    restart: always
    build:
      context: .
    volumes:
      - "./:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - "8000:8000"
    links:
      - mongo

  mongo:
    container_name: cybosium_mongo
    image: mongo
    ports:
      - "27017:27017"

  nginx:
    build:
      context: ./nginx
    container_name: cybosium_nginx
    hostname: cybosium_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      # - ./certbot/letsencrypt/lib:/var/lib/letsencrypt
    depends_on:
      - web

  certbot:
    image: certbot/certbot:arm32v6-latest
    container_name: cybosium_certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email roshanrajeev2001@gmail.com -d api-cybosium.ieeemace.org --agree-tos
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
      # - ./certbot/letsencrypt/lib:/var/lib/letsencrypt
